/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as CompareRouteImport } from "./routes/compare"
import { Route as ExtractionsExtractionIdRouteImport } from "./routes/extractions.$extractionId"
import { Route as ReviewsReviewIdRouteImport } from "./routes/reviews.$reviewId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: "/compare",
  path: "/compare",
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractionsExtractionIdRoute = ExtractionsExtractionIdRouteImport.update({
  id: "/extractions/$extractionId",
  path: "/extractions/$extractionId",
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsReviewIdRoute = ReviewsReviewIdRouteImport.update({
  id: "/reviews/$reviewId",
  path: "/reviews/$reviewId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/extractions/$extractionId": typeof ExtractionsExtractionIdRoute
  "/reviews/$reviewId": typeof ReviewsReviewIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/extractions/$extractionId": typeof ExtractionsExtractionIdRoute
  "/reviews/$reviewId": typeof ReviewsReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/compare": typeof CompareRoute
  "/extractions/$extractionId": typeof ExtractionsExtractionIdRoute
  "/reviews/$reviewId": typeof ReviewsReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/compare"
    | "/extractions/$extractionId"
    | "/reviews/$reviewId"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/compare" | "/extractions/$extractionId" | "/reviews/$reviewId"
  id:
    | "__root__"
    | "/"
    | "/compare"
    | "/extractions/$extractionId"
    | "/reviews/$reviewId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ExtractionsExtractionIdRoute: typeof ExtractionsExtractionIdRoute
  ReviewsReviewIdRoute: typeof ReviewsReviewIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/compare": {
      id: "/compare"
      path: "/compare"
      fullPath: "/compare"
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/extractions/$extractionId": {
      id: "/extractions/$extractionId"
      path: "/extractions/$extractionId"
      fullPath: "/extractions/$extractionId"
      preLoaderRoute: typeof ExtractionsExtractionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reviews/$reviewId": {
      id: "/reviews/$reviewId"
      path: "/reviews/$reviewId"
      fullPath: "/reviews/$reviewId"
      preLoaderRoute: typeof ReviewsReviewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ExtractionsExtractionIdRoute: ExtractionsExtractionIdRoute,
  ReviewsReviewIdRoute: ReviewsReviewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
